version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'microblogAPI'
      SERVER_PORT: 8080
      STORAGE_MODE: 'inmemory'
  database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017