version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'milestone'
      SERVER_PORT: 8080
      STORAGE_MODE: 'inmemory'
      REDIS_URL: 'cache:6379'
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - 27017:27017

  cache:
    image: redis:latest
    ports:
      - 6739:6739