version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'twitterPosts'

  database:
    image: mongo:latest
    ports:
      - 27017:27017